name: CI Build for MacOS Apple silicon
run-name: ${{ github.event.pull_request.title || github.ref_name }} CI Build for MacOS

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run in'
        type: environment
        default: CI
        required: false

env:
  BUILD_TYPE: Release

jobs:
  build_macos-26:
    runs-on: macos-26
    permissions:
      contents: read
      attestations: write
      id-token: write

    steps:
    - name: Configure Git line endings
      run: git config --global core.autocrlf input

    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Grab build dependencies
      run: |
        curl --location --output /tmp/js8lib4.0-MacOS_with_Qt.tar.gz https://github.com/JS8Call-improved/js8lib/releases/download/lib%2F4.0/js8lib4.0-MacOS_with_Qt.tar.gz
        cd /tmp
        tar zxf /tmp/js8lib4.0-MacOS_with_Qt.tar.gz
        sudo mv /tmp/js8lib /usr/local/js8lib

        curl --location --output /tmp/ffmpeg_MacOS_arm64.tar.gz https://github.com/JS8Call-improved/js8lib/releases/download/lib%2F4.0/ffmpeg_MacOS_arm64.tar.gz
        tar zxf /tmp/ffmpeg_MacOS_arm64.tar.gz
        sudo mv /tmp/ffmpeg /usr/local/ffmpeg

    - name: Configure JS8Call
      run: |
        mkdir -p ./build && cd ./build
        cmake -G Xcode -DCMAKE_PREFIX_PATH="/usr/local/js8lib" ..

    - name: Extract version
      run: |
        ver=$(grep "CMAKE_PROJECT_VERSION:STATIC=" build/CMakeCache.txt | cut -d'=' -f2 | tr -d '[:space:]')
        gitHash=$(git rev-parse --short HEAD)

        if [ "$ver" = "0.0.0" ]; then
          safeVer=$gitHash
        else
          safeVer=$ver
        fi

        echo "JS8_SAFE_VER=$safeVer" >> $GITHUB_ENV
        echo "SAFE_VER=$safeVer"

    - name: Build JS8Call
      run: |
        cd ./build
        xcodebuild -scheme JS8Call -configuration Release

    - name: Create DMG
      run: |
        echo "DMG version: ${{ env.JS8_SAFE_VER }}"
        hdiutil create -volname "JS8Call" -srcfolder "build/Release/JS8Call.app" -format UDZO "JS8Call_${{ env.JS8_SAFE_VER }}.dmg"

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: "JS8Call_${{ env.JS8_SAFE_VER }}"
        path: '${{ github.workspace }}/JS8Call_${{ env.JS8_SAFE_VER }}.dmg'
        archive: false
