name: Release Build for Windows 10+ x64
run-name: ${{ github.ref_name }} Release Build for Windows 10+ x64

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build_windows-2025:
    runs-on: windows-2025
    permissions: write-all
    environment: Release

    steps:
    - name: Configure Git line endings
      run: git config --global core.autocrlf input

    - uses: actions/checkout@v5

    - name: Setup Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.1
      with:
        vulkan-query-version: 1.3.204.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.3'
        target: 'desktop'
        arch: 'win64_llvm_mingw'
        modules: 'qtmultimedia qtserialport qtwebsockets qtsvg qtimageformats qtshadertools'
        tools: 'tools_llvm_mingw1706'
        cache: true
        dir: 'D:/a/JS8Call-improved/JS8Call-improved/local/qt693'

    - name: Fetch js8lib
      shell: pwsh
      run: |
        curl -L -o js8lib.zip "https://github.com/JS8Call-improved/js8lib/releases/download/lib%2F3.0/js8lib3.0.1_Win64.zip"
        Expand-Archive js8lib.zip -DestinationPath .

    - name: Setup build directory
      shell: pwsh
      run: mkdir build

    - name: Configure JS8Call
      shell: pwsh
      run: |
        cd build
        $env:Path = "$env:GITHUB_WORKSPACE\js8lib\bin;$env:Path"
        $qt6dir = $env:Qt6_DIR
        $workspace = $env:GITHUB_WORKSPACE
        $llvm = "$env:IQTA_TOOLS\llvm-mingw1706_64\bin"
        $env:Path = "$llvm;$env:Path"
        cmake -G "Ninja Multi-Config" `
          -DCMAKE_C_COMPILER="$llvm\clang.exe" `
          -DCMAKE_CXX_COMPILER="$llvm\clang++.exe" `
          -DQt6_DIR="$qt6dir" `
          -DCMAKE_PREFIX_PATH="$workspace/js8lib/boost-1.88;$workspace/js8lib/hamlib-4.7.1;$workspace/js8lib/fftw3;$workspace/js8lib/libusb-1.0.29" ..

    - name: Extract version
      shell: pwsh
      run: |
        $ver     = (Get-Content build/CMakeCache.txt | Select-String "CMAKE_PROJECT_VERSION:STATIC=(.+)").Matches[0].Groups[1].Value.Trim()
        $gitHash = (git rev-parse --short HEAD).Trim()

        if ($ver -eq "0.0.0") {
          $safeVer = $gitHash
        } else {
          $safeVer = $ver
        }

        echo "JS8_SAFE_VER=$safeVer" >> $env:GITHUB_ENV

    - name: Build JS8Call
      shell: pwsh
      run: |
        cd build
        cmake --build . --config Release

    - name: Move exe and libraries to install directory
      shell: pwsh
      run: |
        cd build
        cp Release\JS8Call.exe JS8Call\
        cp $env:GITHUB_WORKSPACE\js8lib\dll\*.dll JS8Call\
        cp $env:GITHUB_WORKSPACE\LICENSE JS8Call\

    - name: Get signing certificate
      shell: pwsh
      run: |
        echo "${{ secrets.RELEASE_CODE_SIGNING_PFX_BASE64 }}" > 'D:/a/JS8Call-improved/cert.base64'
        certutil -decode 'D:/a/JS8Call-improved/cert.base64' 'D:/a/JS8Call-improved/certificate.pfx'

    - name: Sign binaries
      shell: pwsh
      env:
        PFX_CERTIFICATE_PASSWORD: ${{ secrets.RELEASE_PFX_CERTIFICATE_PASSWORD }}
      run: |
        $signtool = 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64/signtool.exe'
        $cert     = 'D:/a/JS8Call-improved/certificate.pfx'
        cd ./build/JS8Call/
        & $signtool sign /fd SHA256 /v /f $cert /p "$env:PFX_CERTIFICATE_PASSWORD" *.exe
        & $signtool sign /fd SHA256 /v /f $cert /p "$env:PFX_CERTIFICATE_PASSWORD" *.dll

    - name: INNO Setup
      shell: pwsh
      run: |
        $safeVer = "${{ env.JS8_SAFE_VER }}"
        Write-Host "SAFE_VER=$safeVer"
        $issArg = "/DMyAppVersion=$safeVer"
        Write-Host "ISS Arg: $issArg"
        cd ./build/
        & 'C:/Program Files (x86)/Inno Setup 6/ISCC.exe' $issArg "/FJS8Call-$safeVer-installer" ../.github/workflows/scripts/ci-windows-installer.iss

    - name: Sign installer
      shell: pwsh
      env:
        PFX_CERTIFICATE_PASSWORD: ${{ secrets.RELEASE_PFX_CERTIFICATE_PASSWORD }}
      run: |
        $signtool = 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64/signtool.exe'
        $cert     = 'D:/a/JS8Call-improved/certificate.pfx'
        cd ./build/JS8Call/
        & $signtool sign /fd SHA256 /v /f $cert /p "$env:PFX_CERTIFICATE_PASSWORD" JS8Call-*-installer.exe

    - name: Attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: '${{ github.workspace }}/build/JS8Call/*'

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: "JS8Call-${{ env.JS8_SAFE_VER }}-installer"
        path: ./build/JS8Call/JS8Call-*-installer.exe
        archive: false
